name 'linux_patching'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures linux_patching'
long_description 'Installs/Configures linux_patching'
version '0.1.0'
