name 'setup_apache_linux'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures setup_apache_linux'
long_description 'Installs/Configures setup_apache_linux'
version '0.1.0'
